// Generated by gencpp from file wesley_yee_ws/scan_range.msg
// DO NOT EDIT!


#ifndef WESLEY_YEE_WS_MESSAGE_SCAN_RANGE_H
#define WESLEY_YEE_WS_MESSAGE_SCAN_RANGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wesley_yee_ws
{
template <class ContainerAllocator>
struct scan_range_
{
  typedef scan_range_<ContainerAllocator> Type;

  scan_range_()
    : farthest_distance(0.0)
    , closest_distance(0.0)  {
    }
  scan_range_(const ContainerAllocator& _alloc)
    : farthest_distance(0.0)
    , closest_distance(0.0)  {
  (void)_alloc;
    }



   typedef float _farthest_distance_type;
  _farthest_distance_type farthest_distance;

   typedef float _closest_distance_type;
  _closest_distance_type closest_distance;





  typedef boost::shared_ptr< ::wesley_yee_ws::scan_range_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wesley_yee_ws::scan_range_<ContainerAllocator> const> ConstPtr;

}; // struct scan_range_

typedef ::wesley_yee_ws::scan_range_<std::allocator<void> > scan_range;

typedef boost::shared_ptr< ::wesley_yee_ws::scan_range > scan_rangePtr;
typedef boost::shared_ptr< ::wesley_yee_ws::scan_range const> scan_rangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wesley_yee_ws::scan_range_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wesley_yee_ws::scan_range_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wesley_yee_ws::scan_range_<ContainerAllocator1> & lhs, const ::wesley_yee_ws::scan_range_<ContainerAllocator2> & rhs)
{
  return lhs.farthest_distance == rhs.farthest_distance &&
    lhs.closest_distance == rhs.closest_distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wesley_yee_ws::scan_range_<ContainerAllocator1> & lhs, const ::wesley_yee_ws::scan_range_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wesley_yee_ws

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wesley_yee_ws::scan_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wesley_yee_ws::scan_range_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wesley_yee_ws::scan_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wesley_yee_ws::scan_range_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wesley_yee_ws::scan_range_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wesley_yee_ws::scan_range_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wesley_yee_ws::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52cfcfd2a0bc23fbbffa6ecb4b63c13e";
  }

  static const char* value(const ::wesley_yee_ws::scan_range_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52cfcfd2a0bc23fbULL;
  static const uint64_t static_value2 = 0xbffa6ecb4b63c13eULL;
};

template<class ContainerAllocator>
struct DataType< ::wesley_yee_ws::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wesley_yee_ws/scan_range";
  }

  static const char* value(const ::wesley_yee_ws::scan_range_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wesley_yee_ws::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 farthest_distance\n"
"float32 closest_distance\n"
;
  }

  static const char* value(const ::wesley_yee_ws::scan_range_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wesley_yee_ws::scan_range_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.farthest_distance);
      stream.next(m.closest_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct scan_range_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wesley_yee_ws::scan_range_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wesley_yee_ws::scan_range_<ContainerAllocator>& v)
  {
    s << indent << "farthest_distance: ";
    Printer<float>::stream(s, indent + "  ", v.farthest_distance);
    s << indent << "closest_distance: ";
    Printer<float>::stream(s, indent + "  ", v.closest_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WESLEY_YEE_WS_MESSAGE_SCAN_RANGE_H
